package fi.om.municipalityinitiative.util;

public class TestDataTemplateTexts {
    static final String INITIATIVE_1_NAME = "Vähemmän koivuja Joutsan keskustaan";
    static final String INITIATIVE_1_PROPOSAL = "Ehdotan, että Joutsan kirkonkylällä vähennettäisiin koivun käyttöä maisemoinnissa ja siirryttäisiin vähemmän allergisoivien puulajien käyttöön. Minulla on kesäasunto Joutsassa ja joudun välttelemään keskustassa asiointia koko alkukesän ajan";

    static final String INITIATIVE_2_NAME = "Siljonkatu ja Vanhatullinkatun vaaralliset risteykset";
    static final String INITIATIVE_2_PROPOSAL = 
            "1) Ajo Siljonkadulta Peltokadulle on vaarallinen huonon näkyväisyyden vuoksi. Siljonkadun sijainnin (vinoon) vuoksi useat Uusikadun suunnasta Peltokatua ajavat eivät havaitse risteystä lainkaan, jolloin tilannenopeus on suuri. Siljonkadulta tulijalla on väistämisvelvollisuus, mutta sitä on lähes mahdoton noudattaa, koska risteävän liikenteen näkee vasta, kun oma auto on jo puoliksi Peltokadun puolella. Näkemäesteen muodostavat Peltokadun varteen aivan risteykseen asti pysäköidyt autot. Erityisen vaarallinen risteys on Peltokatua pyöräileville. Pyörät tulevat pysäköityjen autojen takaa täysin yllättäen, varsinkin silloin, jos risteyksen lähelle on pysäköity pakettiauto tms. korkeampi auto. Siljonkadulta Peltokadulle tuleva liikenne on lisääntynyt paljon, ja lisääntyy vielä, kun ns. Aurakortteli valmistuu. Siljonkadulta ei ole muuta reittiä pois. Lyhytkin, 1-2 nykyistä parkkipaikkaa, pysäköintikielto Peltokadulle välittömästi risteyksen jälkeen parantaisi huomattavasti liikenneturvallisuutta." +
            "2) Lähes vastaava, mutta vieläkin vaarallisempi paikka, on Vanhantullinkadun ja Ratakadun risteyksessä. Ratakatu on pitkä suora, jossa ajetaan todella lujaa. Tultaessa Vanhatullinkadulta ja käännyttäessä vasemmalle on näkymä oikealta Ratakatua tulevien kaistalle todella heikko. Ratakatu on korkeammalla kuin sille nouseva Vanhatullinkatu, jolloin risteyksessä seisovan ns. normaalin matalan henkilöauton kuljettaja näkee vain pienen pätkän Ratakatua. Tässäkin risteyksessä parkkeeraus on sallittu (parkkipaikka rakennettu) aivan risteykseen kiinni. Alueella on paljon yrityksiä ja usein juuri ko. ensimmäisessä ruudussa seisookin umpinainen pakettiauto, joka peittää täysin näkymän oikealle. Pienempikin auto haittaa näkymää ja jostain käsittämättömästä syystä näkyvyyttä on vielä heikennetty istuttamalla Ratakadun välikorokkeelle melko korkealle nousevia pensaita, joiden taakse hiemankaan matalampi auto häviää täysin. Turvallinen kääntyminen ko. risteyksestä vaatisi kuitenkin, juuri Ratakatua ajavien suuren tilannenopeuden vuoksi, paljon nykyistä pidemmän näkyväisyyden. Ensiapuna tähänkin todella hankalaan risteykseen olisi Ratakadun ensimmäisen oikeanpuoleisen parkkiruudun poistaminen sekä pensaiden vaihtaminen matalampaan kasvillisuuteen.";

}